# Generated by Django 5.2.1 on 2025-06-17 07:40

import django.core.validators
import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('narrator', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, help_text='Okładka audiobooka (JPG, PNG, max 10MB)', null=True, upload_to=users.utils.audiobook_cover_path, validators=[users.utils.validate_image_file])),
                ('duration_minutes', models.PositiveIntegerField()),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='users.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.PositiveIntegerField()),
                ('audio_file', models.FileField(help_text='Plik audio rozdziału (MP3, M4A, WAV, max 500MB)', upload_to=users.utils.audiobook_audio_path, validators=[users.utils.validate_audio_file])),
                ('duration_seconds', models.PositiveIntegerField()),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='users.audiobook')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('audiobook', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='ListeningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position_seconds', models.PositiveIntegerField(default=0)),
                ('last_listened', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.audiobook')),
                ('current_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'audiobook')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'audiobook')},
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'audiobook')},
            },
        ),
    ]
