# Generated by Django 5.2.1 on 2025-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author_category_audiobook_chapter_listeningprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Czy audiobook wymaga zakupu (płatny)', verbose_name='Premium audiobook'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena w PLN (tylko dla premium)', max_digits=6, null=True, verbose_name='Cena'),
        ),
    ]
