# Generated by Django 5.2.1 on 2025-06-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_audiobook_is_premium_audiobook_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Zapłacona cena')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, help_text='ID płatności ze Stripe', max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Oczekująca'), ('completed', 'Zakończona'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona')], default='completed', max_length=20)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zakup',
                'verbose_name_plural': 'Zakupy',
                'unique_together': {('user', 'audiobook')},
            },
        ),
    ]
