# Generated by Django 5.2.1 on 2025-06-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
